apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shopnow-discovery-server
  name: shopnow-discovery-server-deployment
  namespace: microservice-shopnow
spec:
  replicas: 2
  # Các version image đã từng apply
  revisionHistoryLimit: 11
  selector:
    matchLabels:
      app: shopnow-discovery-server
      # deployment match service qua label app: shopnow-discovery-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shopnow-discovery-server
      namespace: microservice-shopnow
    spec:
      containers:
        - image: harbor.nobison.online/shopnow/discovery-server:v1
          imagePullPolicy: Always
          name: shopnow-discovery-server
          ports:
            - containerPort: 8761
              name: tcp
              protocol: TCP
      imagePullSecrets:
        - name: harbor-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: shopnow-discovery-server-service
  namespace: microservice-shopnow
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp
      port: 8761
      protocol: TCP
      targetPort: 8761
  selector:
    app: shopnow-discovery-server
  sessionAffinity: None
  type: ClusterIP

--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopnow-discovery-server-ingress
  namespace: microservice-shopnow
spec:
  ingressClassName: nginx
  rules:
    - host: discovery-shopnow.nnson128.vn
      http:
        paths:
          - backend:
              service:
                name: shopnow-discovery-server-service
                port:
                  number: 8761
            path: /
            pathType: Prefix
